name:                dance-view
version:             0.2.4.4
description:         Various ways of viewing pose network data
homepage:            https://github.com/silky/dance-view#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - diagrams
  - diagrams-cairo
  - diagrams-contrib
  - diagrams-lib
  - diagrams-rasterific
  - diagrams-svg
  - filemanip
  - filepath
  - generic-lens
  - gloss
  - lens
  - optparse-generic
  - random
  - split
  - string-conv
  - text


ghc-options:      
    -threaded -Wall -O2


executables:
    dance-view:
        source-dirs:      src
        main:             Main.hs
        other-modules:    
            - Animation
            - DanceView
            - Data
            - DiagramsDesigns
            - DiagramsStuff
            - Gif
            - Image
            - Smoothing

    gradient-design:
        source-dirs: src
        main: GradientMain.hs
        other-modules:
            - DanceView
            - Data
            - DiagramsStuff


tests:
    spec:
        main: Differences.hs
        source-dirs: 
            - tests
            - src
        dependencies:
            - hspec == 2.*
            - aeson-qq
